name = "Hasper"
license = "MIT"
licenselink = "https://github.com/IanTeda/hasper/blob/master/LICENSE.md"
description = "A hugo clone of the Casper theme for Ghost"
homepage = "https://github.com/IanTeda/hasper"
tags = ['blog','landing page', 'personal']
features = ["google analytics","share"]
min_version = "0.21"

[author]
  name = "Ian Teda"
  homepage = "https://ianteda.com"

[original]
  name = "Casper"
  homepage = "https://github.com/TryGhost/Casper"
  repo = "https://github.com/TryGhost/Casper"
